---
- name: host variabel testing
  hosts: webservers,qaservers
  tasks:
     
    - debug:
        msg: "echo pritn of variale {{ a }} friend for {{ b }}"
      when: "'webservers' in group_names"  

    - yum:
        name: "{{ name }}"
        state: "{{ state }}"
      when: "'qaservers' in group_names"  


