---
- name: install httpd
  hosts: webservers
  become: yes
  gather_facts: yes
  tasks:

  - name: get service status 
    command: systemctl status httpd
    register: result
    ignore_errors: yes
  
  - name: debug service status
    when: result.stdout == "active"
    debug:
     msg: "httpd serive is running"

  - name: uninstall service status
    yum:
     name: httpd
     state: present
    when: result.stdout = "active"
  

 