---
- name: install httpd
  hosts: webservers
  become: yes
  gather_facts: yes
  tasks:

  - name: get service status 
    command: systemctl status httpd
    register: result
    ignore_errors: yes

  - name: debug service status
    when: result.stdout == "active"
    debug:
     msg: "httpd service is running"
    


  - name: start httpd service
    when: result.stdout != "active"
    service:
        name: httpd
        state: started
        enabled: yes
 