---
- name: Installing Java and Maven
  hosts: all
  become: true
  vars_files:
    - variable.yaml  # External variable file

  tasks:
    - name: Install Java
      yum:
        name: "{{ java_package }}"
        state: "{{ state }}"

    - name: Install Maven
      yum:
        name: "{{ maven_package }}"
        state: present
      register: version

    - name: Print Maven version output
      debug:
        var: version
