---
- name: crating rescue and block,always
  hosts: all
  vars:
    webserver: http
    pgadmin: mariadb-server
    db_service: mariadb
  tasks:
   block:
     yum:
      name: {{ webserver }}
      state: present
   rescue:
     - name: print if any fail 
       debug:
        msg: echo "{{ webserver }} got failed"  
   always:
     debug:
       msg: always execute      

      