---
- name: Create users in Linux
  hosts: all
  become: true
  vars_files:
    - var.yaml

  tasks:
    - name: Create user raju
      ansible.builtin.user:
        name: raju
        password: "{{ password }}"
        shell: /bin/bash
