---
- name: host variabel testing
  hosts: webservers,qaservers
  tasks:
    - debug:
        msg: "echo pritn of variale {{ a }} friend for {{ b }}"

    - yum:
        name: "{{ name }}"
        state: "{{ state }}"
        

