---
- name: gatheting facts
  hosts: Qaserver,webservers
  tasks:
   - name: whoami
     shell: whoami
     register: output 
   - name: print ami 
     debug:
       msg: "{{ output.stdout }}"   
     

        
     


