---
- name: install httpd
  hosts: webservers
  become: yes
  gather_facts: no
  tasks:
  - name: install httpd package
    yum:
      name: httpd
      state: present
    notify: start httpd service   
  handlers:    
  - name: start httpd service
    service:
        name: httpd
        state: started
        enabled: yes
             
