---
- name: Loops of packages
  hosts: all
  become: true

  tasks:
    - name: Installing security packages
      package:
        name: "{{ item }}"
        state: present
      loop:
        - auditd
        - aide
        - firewalld
