---
- name: gatheting facts
  hosts: Qaserver,webservers
  become: true

  tasks:
  - name: whoami
    shell: whoami
    register: output
  - name: print ami
    debug:
      msg: "{{ output.stdout }}"
  - name: print some file 
    debug: 
      msg: "{{ lookup('file', '/etc/ansible/ansible.log') }}"


