---
- name: install httpd
  hosts: webservers
  become: yes
  gather_facts: yes
  tasks:

  - name: get service status 
    command: systemctl status httpd
    register: result
    ignore_errors: yes

  - name: debug service status
    debug:
     msg: httpd service is running"
    when: result.stdout == "active"


  - name: start httpd service
    service:
        name: httpd
        state: started
        enabled: yes
    when: result.result.stdout != "active"