---
- name: install httpd
  hosts: webservers
  become: yes
  gather_facts: yes
  tasks:

  - name: get service status 
    command: systemctl status httpd.service
    register: result
    ignore_errors: yes
  
  - name: debug service status
    when: result.stdout == "active" 
    debug:
     msg: "httpd serive is running"

  - name: uninstall service status
    yum:
     name: httpd
     state: absent
    when: result.stdout == "active"

  - name: check again status
    command: systemctl status httpd.service 
    register: final
    ignore_errors: yes

  - name: debug
    debug:
      msg: "echo {{ final }}"  

 