---
- name: Loops of packages
  hosts: all
  become: true

  tasks:
    - name: creating users in servers
      user:
        name: "{{ item.name }}"
        uid: "{{ item.access }}"
      loop:
        - { name: 'hari' , access: '0777'}
        - { name: 'srinu' , access: '0644'}
        - { name: 'priya' , access: '0444'}
