---
- name: Installing Java and Maven
  hosts: all
  become: true
  vars_files:
    - variable.yaml  # External variable file

  tasks:
    - name: Install Java
      yum:
        name: "{{ java_package }}"
        state: "{{ stage_1 }}"

    - name: Install Maven
      yum:
        name: "{{ maven_package }}"
        state: "{{ stage_2 }}"

    - name: Get Maven version
      shell: mvn -v
      register: maven_version_output
      changed_when: false  # Don't mark as "changed" every time

    - name: Print Maven version
      debug:
        var: maven_version_output.stdout_lines
