---
- name: Installing Java and Maven
  hosts: all
  become: true
  vars_files:
    - variable.yaml  # This is the correct way to include external vars

  tasks:
    - name: Install Java
      yum:
       name: "{{ java_package }}"
       state: present

    - name: Install Maven
      yum:
        name: "{{ maven_package }}"
        state: present
