---
- name: Installing Java
  hosts: all
  become: true
  vars:
    java_package: java-1.8.0-openjdk
  tasks:
    - name: Install Java
      yum:
        name: "{{ java_package }}"
        state: present

    - name: Check Java version
      shell: java -version
      register: java_version_output
      ignore_errors: true

    - name: Print Java version output
      debug:
        var: java_version_output.stderr_lines
